# Travis CI integration -- https://travis-ci.org/troglobit/crobots
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Build on both Linux and macOS
os:
 - linux
 - osx

# Verify on macOS X 10.11 -- https://docs.travis-ci.com/user/reference/osx/
osx_image: xcode7.3

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

# Custom build script for the time being, no "make test" yet
script:
  - ./autogen.sh
  - ./configure --prefix=/tmp/crobots
  - make clean
  - make -j5
  - make distcheck
  - make install-strip
  - ls -lR /tmp/crobots
  - ldd /tmp/crobots/bin/crobots || otool -L /tmp/crobots/bin/crobots
  - /tmp/crobots/bin/crobots -h
